### ISSUE TITLE
Internal audit fixes

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#369]
## [Low severity Issues](https://hackmd.io/@blockdev/Sk6jC9mCs#low-severity-issues)

   - [x] [1. Polysum.add() allows any value for vals[i]](https://hackmd.io/@blockdev/Sk6jC9mCs#1-polysumadd-allows-any-value-for-valsi)
   - [x] [2. Use version 0x00 for signature verification](https://hackmd.io/@blockdev/Sk6jC9mCs#2-use-version-0x00-for-signature-verification)
   - [x] [3. Fix TODO for signature verification](https://hackmd.io/@blockdev/Sk6jC9mCs#3-fix-todo-for-signature-verification)

## [Constraint optimization](https://hackmd.io/@blockdev/Sk6jC9mCs#constraint-optimization)

   - [x] [1. Bit length constraint on nonce can be avoided](https://hackmd.io/@blockdev/Sk6jC9mCs#1-bit-length-constraint-on-nonce-can-be-avoided)
   - [x] [2. epoch is explicitly constrained to 64 bits](https://hackmd.io/@blockdev/Sk6jC9mCs#2-epoch-is-explicitly-constrained-to-64-bits)

## [Gas optimization](https://hackmd.io/@blockdev/Sk6jC9mCs#gas-optimization)

   - [x] [1. Use lateset @zk-kit/incremental-merkle-tree.sol](https://hackmd.io/@blockdev/Sk6jC9mCs#1-use-lateset-zk-kitincremental-merkle-treesol)
  - [x] [2. SafeMath not required for solc>=v0.8](https://hackmd.io/@blockdev/Sk6jC9mCs#2-safemath-not-required-for-solcv08)
   - [x] [3. Use calldata for all arguments](https://hackmd.io/@blockdev/Sk6jC9mCs#3-use-calldata-for-all-arguments)
   - [x] [4. Constant variables can be used in assembly directly](https://hackmd.io/@blockdev/Sk6jC9mCs#4-constant-variables-can-be-used-in-assembly-directly)
   - [x] [5. No need to save gas for execution after staticcall to 0x05](https://hackmd.io/@blockdev/Sk6jC9mCs#5-no-need-to-save-gas-for-execution-after-staticcall-to-0x05)
   - [x] [6. _updateEpochIfNeeded() can be made internal](https://hackmd.io/@blockdev/Sk6jC9mCs#6-_updateepochifneeded-can-be-made-internal)
   - [x] [7. Check on attestorId not needed](https://hackmd.io/@blockdev/Sk6jC9mCs#7-check-on-attestorid-not-needed)

## [Informational issues](https://hackmd.io/@blockdev/Sk6jC9mCs#informational-issues)

   - [x] [1. Use address(this) to read contract’s address](https://hackmd.io/@blockdev/Sk6jC9mCs#1-use-addressthis-to-read-contracts-address)
  - [x]  [2. Remove useless files](https://hackmd.io/@blockdev/Sk6jC9mCs#2-remove-useless-files)
   - [x] [6. lt_comp and leaf_mux signal arrays can be reduced by 1 element](https://hackmd.io/@blockdev/Sk6jC9mCs#6-lt_comp-and-leaf_mux-signal-arrays-can-be-reduced-by-1-element)
   - [x] [7. hasher_index can be removed and i can be used directly](https://hackmd.io/@blockdev/Sk6jC9mCs#7-hasher_index-can-be-removed-and-i-can-be-used-directly)
   - [x] [8. state_tree_elements can be made a 1d array](https://hackmd.io/@blockdev/Sk6jC9mCs#8-state_tree_elements-can-be-made-a-1d-array)
